#!/usr/bin/env python3
"""Write the texture and the station model for one or more AprilTag ids.

Not a ROS node and not installed: run it from the package source tree, and
commit what it produces.

    python3 tools/make_tag_textures.py 0 1 2

Both outputs come from rospider_gazebo/tags.py, so the rendered tag and the
board it is stretched across can never disagree about scale.
"""

import argparse
import os
import sys

import cv2

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rospider_gazebo import tags  # noqa: E402  (needs the sys.path above)

PKG_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def station_sdf(tag_id):
    """The SDF text for tag_station_<id>.

    Static, box geometry only, no meshes -- the same shape as
    models/pick_pedestal, and for the same reason: gazebo.launch.py strips
    mesh collisions because the robot's own STLs are 1.5M triangles, and
    scenery that needs the same treatment would be a trap.

    The model faces +x: a robot approaching from +x sees the tag.
    """
    px, py, pz = tags.PEDESTAL_SIZE
    ox, oy, oz = tags.POST_SIZE
    face = tags.BOARD_FACE
    board = f'{tags.BOARD_THICKNESS:.6f} {face:.6f} {face:.6f}'
    return f'''<?xml version="1.0"?>
<sdf version="1.9">
  <!-- Generated by tools/make_tag_textures.py. Edit that, not this. -->
  <model name="tag_station_{tag_id}">
    <static>true</static>
    <link name="link">
      <collision name="pedestal_c">
        <pose>0 0 {pz / 2:.6f} 0 0 0</pose>
        <geometry><box><size>{px:.6f} {py:.6f} {pz:.6f}</size></box></geometry>
      </collision>
      <visual name="pedestal_v">
        <pose>0 0 {pz / 2:.6f} 0 0 0</pose>
        <geometry><box><size>{px:.6f} {py:.6f} {pz:.6f}</size></box></geometry>
        <material>
          <ambient>0.6 0.6 0.62 1</ambient>
          <diffuse>0.6 0.6 0.62 1</diffuse>
        </material>
      </visual>
      <collision name="post_c">
        <pose>{tags.BOARD_OFFSET_X:.6f} 0 {oz / 2:.6f} 0 0 0</pose>
        <geometry><box><size>{ox:.6f} {oy:.6f} {oz:.6f}</size></box></geometry>
      </collision>
      <visual name="post_v">
        <pose>{tags.BOARD_OFFSET_X:.6f} 0 {oz / 2:.6f} 0 0 0</pose>
        <geometry><box><size>{ox:.6f} {oy:.6f} {oz:.6f}</size></box></geometry>
        <material>
          <ambient>0.3 0.3 0.32 1</ambient>
          <diffuse>0.3 0.3 0.32 1</diffuse>
        </material>
      </visual>
      <collision name="board_c">
        <pose>{tags.BOARD_OFFSET_X:.6f} 0 {tags.TAG_CENTRE_HEIGHT:.6f} 0 0 0</pose>
        <geometry><box><size>{board}</size></box></geometry>
      </collision>
      <visual name="board_v">
        <pose>{tags.BOARD_OFFSET_X:.6f} 0 {tags.TAG_CENTRE_HEIGHT:.6f} 0 0 0</pose>
        <geometry><box><size>{board}</size></box></geometry>
        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <pbr><metal>
            <albedo_map>../../worlds/textures/tag_{tag_id}.png</albedo_map>
            <roughness>0.9</roughness>
            <metalness>0</metalness>
          </metal></pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
'''


def write_station(tag_id, module_px):
    texture_dir = os.path.join(PKG_ROOT, 'worlds', 'textures')
    model_dir = os.path.join(PKG_ROOT, 'models', f'tag_station_{tag_id}')
    os.makedirs(model_dir, exist_ok=True)

    texture = os.path.join(texture_dir, f'tag_{tag_id}.png')
    cv2.imwrite(texture, tags.generate_tag_image(tag_id, module_px))

    model = os.path.join(model_dir, 'model.sdf')
    with open(model, 'w') as handle:
        handle.write(station_sdf(tag_id))

    return texture, model


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('ids', type=int, nargs='+', help='tag36h11 ids')
    parser.add_argument('--module-px', type=int, default=40,
                        help='pixels per tag module (default 40)')
    args = parser.parse_args()
    for tag_id in args.ids:
        for path in write_station(tag_id, args.module_px):
            print(f'wrote {os.path.relpath(path, PKG_ROOT)}')


if __name__ == '__main__':
    main()
