#!/usr/bin/env python3
"""Write worlds/mission_challenge.sdf: worlds/slam_challenge.sdf plus the two tag stations and the
pick pedestals and the
yellow pad of rospider_gazebo/mission_check.py (the final mission's scene). The blocks are
dynamic, so the launch spawns them.

    PYTHONPATH=. python3 tools/make_mission_world.py
"""
import pathlib

from rospider_gazebo import mission_check, stations

PKG = pathlib.Path(__file__).resolve().parents[1]
HEADER = '''<!-- The final mission's scene (docs/superpowers/specs/2026-09-29-mission-challenge-design.md).
     Generated by tools/make_mission_world.py from worlds/slam_challenge.sdf and
     rospider_gazebo/mission_check.py; edit those. -->
'''


def _station(tag, x, y, yaw):
    sdf = stations.station_sdf(tag)
    model = sdf[sdf.index('<model'):sdf.rindex('</model>') + len('</model>')]
    model = model.replace('../../worlds/textures/', 'textures/')
    return '    ' + model.replace('<static>true</static>',
                                  f'<pose>{x} {y} 0 0 0 {yaw:.5f}</pose>\n    <static>true</static>', 1)


def _pedestal(tag):
    x, y, yaw = mission_check.pick_pedestal(tag)
    sdf = (PKG / 'models' / 'pick_pedestal' / 'model.sdf').read_text()
    model = sdf[sdf.index('<model'):sdf.rindex('</model>') + len('</model>')]
    model = model.replace('<model name="pick_pedestal">', f'<model name="pick_pedestal_{tag}">', 1)
    return '  ' + model.replace('<static>true</static>',
                                f'<pose>{x:.4f} {y:.4f} 0.04 0 0 {yaw:.5f}</pose>\n    <static>true</static>', 1)


def _pad():
    x, y = mission_check.PAD
    size = mission_check.PAD_SIZE
    return f'''    <model name="mission_pad">
      <pose>{x} {y} 0.001 0 0 0</pose>
      <static>true</static>
      <link name="link"><visual name="v"><geometry><box><size>{size} {size} 0.002</size></box></geometry>
        <material><ambient>0.95 0.85 0.1 1</ambient><diffuse>0.95 0.85 0.1 1</diffuse></material></visual></link>
    </model>'''


def build():
    maze = (PKG / 'worlds' / 'slam_challenge.sdf').read_text()
    body = maze[maze.index('<sdf'):maze.rindex('  </world>')]
    body = body.replace('<world name="slam_challenge">', '<world name="mission_challenge">', 1)
    extra = [_station(tag, *pose) for tag, pose in mission_check.STATIONS.items()]
    extra += [_pedestal(tag) for tag in mission_check.STATIONS] + [_pad()]
    return '<?xml version="1.0"?>\n' + HEADER + body + '\n'.join(extra) + '\n  </world>\n</sdf>\n'


def main():
    (PKG / 'worlds' / 'mission_challenge.sdf').write_text(build())


if __name__ == '__main__':
    main()
