#!/usr/bin/env python3
"""Write worlds/apriltag_challenge.sdf: the colour exercise's bare floor and sun, and one tag
station per entry of rospider_gazebo/tag_check.py's STATIONS, embedded (stations.station_sdf with
the texture path made relative to worlds/), as worlds/rospider_room.sdf embeds its station.

    PYTHONPATH=. python3 tools/make_apriltag_world.py
"""
import pathlib

from rospider_gazebo import stations
from rospider_gazebo.tag_check import STATIONS, TARGET

PKG = pathlib.Path(__file__).resolve().parents[1]
HEADER = f'''<?xml version="1.0"?>
<!-- The AprilTag Tracking exercise's scene (docs/superpowers/specs/2026-09-29-apriltag-challenge-design.md).
     Generated by tools/make_apriltag_world.py from rospider_gazebo/tag_check.py's STATIONS; edit those.
     Three tag stations face the spawn point; the robot must walk to tag {TARGET}. No walls, no posters. -->
'''


def main():
    color = (PKG / 'worlds' / 'color_challenge.sdf').read_text()
    head = color[color.index('<sdf'):color.index('    <model name="ground_plane">')]
    ground = color[color.index('    <model name="ground_plane">'):color.index('    <model name="red_target">')]
    body = ''
    for tag, (x, y, yaw) in STATIONS.items():
        sdf = stations.station_sdf(tag)
        model = sdf[sdf.index('<model'):sdf.rindex('</model>') + len('</model>')]
        model = model.replace('../../worlds/textures/', 'textures/')
        model = model.replace('<static>true</static>',
                              f'<pose>{x} {y} 0 0 0 {yaw:.5f}</pose>\n    <static>true</static>', 1)
        body += '    ' + model + '\n'
    world = HEADER + head.replace('color_challenge', 'apriltag_challenge') + ground + body
    (PKG / 'worlds' / 'apriltag_challenge.sdf').write_text(world + '  </world>\n</sdf>\n')


if __name__ == '__main__':
    main()
